print("Installing... Please Wait...")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/Quiologin.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/update.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/QuioShell.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/startup.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/hometab.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/iconlauncher.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/adduser.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/mode.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/Quiologin.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/update.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/QuioShell.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/startup.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/iconlauncher.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/adduser.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/APIs/QuioAPI.lua /APIs/QuioAPI.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/APIs/QuioWindow.ico /APIs/QuioWindow.ico")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/APIs/err.ico /APIs/err.ico")
shell.run("wget https://raw.githubusercontent.com/kazu55/QuioShell/master/startup.ico /startup.ico")
shell.run("reboot")
