os.fadeout = function(time)
  term.setBackgroundColor(colors.white)
  term.clear()
  sleep(time)
  term.setBackgroundColor(colors.lightBlue)
  term.clear()
  sleep(time)
  term.setBackgroundColor(colors.lightGray)
  term.clear()
  sleep(time)
  term.setBackgroundColor(colors.gray)
  term.clear()
  sleep(time)
  term.setBackgroundColor(colors.black)
  term.clear()
  sleep(time)
end

local function centerText(text)
  local x,y = term.getSize()
  local x2, y2 = term.getCursorPos()
  term.setCursorPos(math.ceil((x / 2) - (text:len() / 2)), y2)
  write(text)
end

local reboot = os.reboot

os.reboot = function()
  term.setBackgroundColor(colors.white)
  term.setTextColor(colors.black)
  term.clear()
  term.setCursorPos(1, 2)
  centerText("Shutting down")
  sleep(1)
  os.fadeout(0.1)
  term.setTextColor(colors.white)
  centerText(">_<")
  sleep(1)
  centerText("\7_\7")
  sleep(0.1)
  centerText("-_-")
  sleep(0.1)
  centerText("\7_\7")
  sleep(0.1)
  centerText("-_-")
  sleep(0.1)
  centerText("\7_\7")
  sleep(0.1)
  centerText("-_-")
  sleep(0.1)
  centerText("\7_\7")
  sleep(0.25)
  centerText("-_-")
  sleep(1)
  term.clear()
  sleep(1)
  reboot()
  while true do
    coroutine.yield()
  end
end

local shutdown = os.shutdown

os.shutdown = function()
  term.setBackgroundColor(colors.white)
  term.setTextColor(colors.black)
  term.clear()
  term.setCursorPos(1, 2)
  centerText("Shutting down")
  sleep(1)
  os.fadeout(0.1)
  term.setTextColor(colors.white)
  centerText(">_<")
  sleep(1)
  centerText("\7_\7")
  sleep(0.1)
  centerText("-_-")
  sleep(0.1)
  centerText("\7_\7")
  sleep(0.1)
  centerText("-_-")
  sleep(0.1)
  centerText("\7_\7")
  sleep(0.1)
  centerText("-_-")
  sleep(0.1)
  centerText("\7_\7")
  sleep(0.25)
  centerText("-_-")
  term.setCursorPos(1, 4)
  centerText("See you again!")
  sleep(1)
  term.clear()
  sleep(1)
  shutdown()
  while true do
    coroutine.yield()
  end
end

term.clear()
centerText("-_-")
sleep(1)
centerText("\7_\7")
sleep(0.0)
centerText("-_-")
sleep(0.1)
centerText("\7_\7")
sleep(0.1)
centerText("-_-")
sleep(0.1)
centerText("\7_\7")
sleep(0.1)
centerText("-_-")
sleep(0.1)
centerText("\7_\7")
sleep(0.25)
centerText(">_<")
sleep(0.5)
term.setCursorPos(1, 4)
if math.random(1, 7) == 1 then
  centerText("hello! Please login.")
elseif math.random(1, 7) == 2 then
  centerText("Hello! How are you?")
elseif math.random(1, 7) == 3 then
  centerText("What your name?")
elseif math.random(1, 7) == 4 then
  centerText("my name is martine.")
elseif math.random(1, 7) == 5 then
  centerText("bug? report to github issues!")
elseif math.random(1, 7) == 6 then
  centerText("Maybe I'm fictitious?")
elseif math.random(1, 7) == 7 then
  centerText("Maybe I'm programmed?")
else
  centerText("Hello!")
end
sleep(1)
shell.run("/Quiologin.lua")
